package co.edu.poli.salud.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TypeDocumentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeDocumentAllPropertiesEquals(TypeDocument expected, TypeDocument actual) {
        assertTypeDocumentAutoGeneratedPropertiesEquals(expected, actual);
        assertTypeDocumentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeDocumentAllUpdatablePropertiesEquals(TypeDocument expected, TypeDocument actual) {
        assertTypeDocumentUpdatableFieldsEquals(expected, actual);
        assertTypeDocumentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeDocumentAutoGeneratedPropertiesEquals(TypeDocument expected, TypeDocument actual) {
        assertThat(expected)
            .as("Verify TypeDocument auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeDocumentUpdatableFieldsEquals(TypeDocument expected, TypeDocument actual) {
        assertThat(expected)
            .as("Verify TypeDocument relevant properties")
            .satisfies(e -> assertThat(e.getInitials()).as("check initials").isEqualTo(actual.getInitials()))
            .satisfies(e -> assertThat(e.getDocumentName()).as("check documentName").isEqualTo(actual.getDocumentName()))
            .satisfies(e -> assertThat(e.getStateTypeDocument()).as("check stateTypeDocument").isEqualTo(actual.getStateTypeDocument()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeDocumentUpdatableRelationshipsEquals(TypeDocument expected, TypeDocument actual) {}
}
